spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/http_conform}
    username: ${SPRING_DATASOURCE_USERNAME:http_conform}
    password: ${SPRING_DATASOURCE_PASSWORD:http_conform}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:}
          jwk-set-uri: ${JWT_JWK_SET_URI:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
